#pragma once

// ============================================================
// MINIMAL NUMPY .NPY FLOAT32 2D READER
// ============================================================
//
// Supports:
//   np.save() output
//   little-endian float32
//   C-order 2D arrays
//
// Used for reading xmap.npy and ymap.npy generated by Python.
//
// ============================================================

#include <fstream>
#include <iostream>
#include <regex>
#include <stdexcept>
#include <string>
#include <vector>

#include <opencv2/opencv.hpp>

static cv::Mat read_npy_float32_2d(
    const std::string& path,
    int expected_width,
    int expected_height
) {
    std::ifstream f(path, std::ios::binary);

    if (!f) {
        throw std::runtime_error("Cannot open npy file: " + path);
    }

    char magic[6];
    f.read(magic, 6);

    if (std::string(magic, 6) != "\x93NUMPY") {
        throw std::runtime_error("Invalid npy magic header: " + path);
    }

    unsigned char major = 0;
    unsigned char minor = 0;

    f.read(reinterpret_cast<char*>(&major), 1);
    f.read(reinterpret_cast<char*>(&minor), 1);

    uint32_t header_len = 0;

    if (major == 1) {
        uint16_t h16 = 0;
        f.read(reinterpret_cast<char*>(&h16), 2);
        header_len = h16;
    } else if (major == 2 || major == 3) {
        uint32_t h32 = 0;
        f.read(reinterpret_cast<char*>(&h32), 4);
        header_len = h32;
    } else {
        throw std::runtime_error("Unsupported npy version in: " + path);
    }

    std::string header(header_len, ' ');
    f.read(&header[0], header_len);

    if (
        header.find("'descr': '<f4'") == std::string::npos &&
        header.find("\"descr\": \"<f4\"") == std::string::npos &&
        header.find("'descr': '|f4'") == std::string::npos
    ) {
        throw std::runtime_error("Only float32 npy files are supported: " + path);
    }

    if (header.find("False") == std::string::npos) {
        throw std::runtime_error("Fortran-order npy is not supported: " + path);
    }

    std::regex shape_regex("\\(([0-9]+),\\s*([0-9]+)\\)");
    std::smatch match;

    if (!std::regex_search(header, match, shape_regex)) {
        throw std::runtime_error("Could not parse npy shape: " + path);
    }

    int height = std::stoi(match[1]);
    int width = std::stoi(match[2]);

    if (width != expected_width || height != expected_height) {
        throw std::runtime_error(
            "Npy shape mismatch in " + path +
            ". Expected " + std::to_string(expected_width) + "x" + std::to_string(expected_height) +
            ", got " + std::to_string(width) + "x" + std::to_string(height)
        );
    }

    cv::Mat mat(height, width, CV_32FC1);

    const size_t bytes = static_cast<size_t>(width) *
                         static_cast<size_t>(height) *
                         sizeof(float);

    f.read(reinterpret_cast<char*>(mat.data), bytes);

    if (!f) {
        throw std::runtime_error("Failed to read npy data: " + path);
    }

    return mat;
}
